### ISSUE TITLE
The existence of this project

### ISSUE THREAD

**Issue by alek-shirar** [MultiCraftProject/MultiCraft#132]

**Comment by AidanLCB** [comment]
A lot of the people who work on this also work on minetest, I wish that they would add the good stuff from multicraft to minetest instead of forcing people to use this, such as the improved controls in the mobile app. I also hate the amount of ads in an open source minetest based game, minetest should not be associated with all the cheap games on the play store with a million ads or games that are clearly ripoffs of other games.

**Comment by MoNTE48** [comment]
> I wish that they would add the good stuff from multicraft to minetest

What kind of stuff are you talking about?

> instead of forcing people to use this

Who forces you to use MultiCraft with superior performance, a nice user interface and the ability to compile a game from a source without ads, using any OS instead of using Minetest?

> minetest should not be associated with all the cheap games

What do I have to do with the cheap games that you are talking about and why did you come to me with this?

**Comment by AidanLCB** [comment]
I do really like the controls of MultiCraft compared to the controls in the standard mobile app, I would love it if these controls were added to the main game (with more configuration such as sensitivity) especially as these 2 projects share multiple developers. I don't know what you are talking about with "superior performance", on my cheap chinese phone Minetest 5.3 runs much better then MultiCraft. By cheap games I mean all the games on the play store littered with ads and that are clearly trying to be other games such as Minecraft, I don't like how many Minetest forks there are like this because they can hurt Minetest's reputation in my opinion.

**Comment by MoNTE48** [comment]
The current controls of MultiCraft is made by me personally, I am not a Minetest developer.
Minetest 5.3 and its performance are possible thanks to my (MultiCraft main developer and owner) efforts to backporting many improvements from MultiCraft to Minetest.
And if I didn’t receive messages from people like you, I would do even more for Minetest. My contribution to Minetest 5.3 (contribution is taken into account only from the moment development 5.3 begins - April 5, 2020):
![image](https://user-images.githubusercontent.com/6764600/86036606-6eed3700-ba3e-11ea-9b4d-e35583a73e8b.png)
I planned to make backport controls and even more fixes and improvements from MultiCraft to Minetest 5.4.0. But your message shows that people do not appreciate my contributions.

**Comment by AidanLCB** [comment]
I feel like you are missing some of what I said, I specifically said that I wanted the controls from MultiCraft in minetest, and that I wanted the devs to work together more instead of creating separate forks, I was more upset with the excessive ads, as well as it trying to be even more of a Minecraft clone making it seem like a cheap ripoff.

**Comment by MoNTE48** [comment]
1) As I said, I planned to transfer control from MultiCraft to Minetest later. I did not have enough time to do this in 5.3.0. MultiCraft is based on Minetest 0.4 and backporting each stuffs is really time consuming. Some things were done many years ago and I just don’t remember the details. In 90% of cases Backport from MultiCraft to Minetest = code same thing, but from scratch!
2) MultiCraft shows ads only in a single player game. If you see ads in multiplayer, you download not official MultiCraft. MultiCraft was developed as the Lua subgame for Minetest. (This is my vision of my game. If you personally don’t like my “clone”, do not download it.) But since my vision of the game does not coincide with the goals of Minetest Devs, I have to create my own fork. If it’s very simplistic: I suggest adding something - they tell me that it will not be added. Or the addition of some function may take half a year or more. I am not ready to put up with such a slow development.
3) If you want to play without ads, you can compile MultiCraft yourself on any platform. Linux, Windows, macOS, ChromeOS?
