### ISSUE TITLE
Is MultiCraft compatible with Minetest and vice versa ?

### ISSUE THREAD

**Issue by appgurueu** [MultiCraftProject/MultiCraft#143]

**Comment by MoNTE48** [comment]
multicraft supports 100% minetest 0.4.17 features.  But multicraft subgame may not work as expected in minetest 0.4.17 due to changes in builtin.  Compatibility of minetest client with MultiCraft servers 99%.  Some functions ported from minetest 5.0 do not work.

**Comment by MoNTE48** [comment]
From the functions that come to mind.  Minetest player 0.4.17 will have an advantage over a multicraft player.  It will not suffocate inside blocks, slide on ice or slow down in the snow.  This is from playerplus mod.  I transferred these functions to the engine so that they work faster.  sliding function ported from minetest 5.0.  If there are 9 inventory cells (hud) or more on the server, the MultiCraft player will see only 8 anyway. More than 8 is not supported in touchscreengui, and they will not fit on the screen either.
